### ISSUE TITLE
Create storyboard for content creator user type

### ISSUE THREAD

**Issue by meiqimichelle** [CodeForTucson/wizardmaker#2]
@pdtynan has a draft powerpoint with storyboards for several user types. We need to pull out the information for the highest risk path (the content creator) and make a first draft storyboard for that one.

**Comment by pdtynan** [comment]
I added notes to the draft on Google but we also have to add features for the features that part of the minimum viable product. For now that means branching and calculations. The other function, video clips, is already in the storyboard. 
Hmm, what tool to use? I think I used ForUI because I happened to own it but I might switch to Balsamiq or something commonly used by others in Code for Tucson.

**Comment by pdtynan** [comment]
On Michelle's advise I will use Sketch to update these. We can discuss whether Invision is powerful enough for a usability prototype.
